// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using MyApp.Persistence.Database;

#nullable disable

namespace MyApp.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyApp.Domain.Entities.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Policies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3d990739-98f0-f047-8796-fb1770b5c803"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreationAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Permission for Policies.Users.Create",
                            DisplayName = "Create",
                            Group = "Users",
                            IsActive = true,
                            Name = "Policies.Users.Create"
                        },
                        new
                        {
                            Id = new Guid("2beb0e5f-415c-6042-8fe2-9614a1a1aac4"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreationAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Permission for Policies.Users.Update",
                            DisplayName = "Update",
                            Group = "Users",
                            IsActive = true,
                            Name = "Policies.Users.Update"
                        },
                        new
                        {
                            Id = new Guid("b4f8a89a-6c23-344c-8504-da60ae9d22b6"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreationAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Permission for Policies.Users.Delete",
                            DisplayName = "Delete",
                            Group = "Users",
                            IsActive = true,
                            Name = "Policies.Users.Delete"
                        },
                        new
                        {
                            Id = new Guid("7919fc92-643b-2d45-adac-4dd5c5b45837"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreationAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Permission for Policies.Users.View",
                            DisplayName = "View",
                            Group = "Users",
                            IsActive = true,
                            Name = "Policies.Users.View"
                        },
                        new
                        {
                            Id = new Guid("f63bc3af-aee8-5d4b-8b32-00b7b5d90c01"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreationAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Permission for Policies.Users.List",
                            DisplayName = "List",
                            Group = "Users",
                            IsActive = true,
                            Name = "Policies.Users.List"
                        },
                        new
                        {
                            Id = new Guid("2a077084-536c-3d44-914c-65adc0acc523"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreationAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Permission for Policies.Tenants.Create",
                            DisplayName = "Create",
                            Group = "Tenants",
                            IsActive = true,
                            Name = "Policies.Tenants.Create"
                        },
                        new
                        {
                            Id = new Guid("01a8ea06-74f9-e74d-bae7-dac9ab103c15"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreationAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Permission for Policies.Tenants.Update",
                            DisplayName = "Update",
                            Group = "Tenants",
                            IsActive = true,
                            Name = "Policies.Tenants.Update"
                        },
                        new
                        {
                            Id = new Guid("3e9a80b2-3ec5-a546-a4cb-dd13f5601251"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreationAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Permission for Policies.Tenants.Delete",
                            DisplayName = "Delete",
                            Group = "Tenants",
                            IsActive = true,
                            Name = "Policies.Tenants.Delete"
                        },
                        new
                        {
                            Id = new Guid("ca24d9f8-1326-c34b-ba86-d8d969823e8c"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreationAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Permission for Policies.Tenants.View",
                            DisplayName = "View",
                            Group = "Tenants",
                            IsActive = true,
                            Name = "Policies.Tenants.View"
                        },
                        new
                        {
                            Id = new Guid("08ab7303-9b66-9047-bad1-60193b07d025"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreationAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Permission for Policies.Tenants.List",
                            DisplayName = "List",
                            Group = "Tenants",
                            IsActive = true,
                            Name = "Policies.Tenants.List"
                        });
                });

            modelBuilder.Entity("MyApp.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("308660dc-ae51-480f-824d-7dca6714c3e2"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreationAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Administrator role with full access",
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("MyApp.Domain.Entities.RolePolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId");

                    b.HasIndex("RoleId", "PolicyId")
                        .IsUnique();

                    b.ToTable("RolePolicies");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreationAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreationAt");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("EmailAddress");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("FirstName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModifiedAt");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifiedBy");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("LastName");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("PasswordSalt");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("PhoneNumber");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("EmailAddress")
                        .IsUnique()
                        .HasDatabaseName("EmailAddress");

                    b.HasIndex("TenantId");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("017f22e6-bb67-7e17-8a60-9f822a22a3e1"),
                            CreatedBy = new Guid("017f22e6-bb67-7e17-8a60-9f822a22a3e1"),
                            CreationAt = new DateTime(2024, 10, 15, 3, 3, 39, 0, DateTimeKind.Utc),
                            EmailAddress = "mahammad.azimzada@gmail.com",
                            FirstName = "Mahammad",
                            IsActive = true,
                            LastName = "Azimzada",
                            PasswordHash = "cwnM71bM4LdWaVs/1dUvaOQHrZh4ZCli3XX1TEK3UDuDNYG9GLPvEFefUSP3mi/rcEbniYMhIXt44lRLfheUnA==",
                            PasswordSalt = "3ug03IvjXIHkzVGAk+x/TZ4nAophlLeJcaWBWzpzWsPSKYOWDsBi9eU9C0/09Vemza7GFL3d1NaRKUJelhYqNrCjgPFrBQGGYCJZK71ST+xSWCCem/MaXzoDGY3soMlKc6L+89D6squSOdnQYieYklDvXR+hEeEt9U0X+c3SqFs=",
                            PhoneNumber = "+994509888128"
                        });
                });

            modelBuilder.Entity("MyApp.Domain.Entities.UserDeviceSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DeviceId")
                        .IsUnique();

                    b.ToTable("UserDeviceSessions", (string)null);
                });

            modelBuilder.Entity("MyApp.Domain.Entities.UserExternalLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserExternalLogins");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.RolePolicy", b =>
                {
                    b.HasOne("MyApp.Domain.Entities.Policy", "Policy")
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApp.Domain.Entities.Role", "Role")
                        .WithMany("RolePolicies")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.User", b =>
                {
                    b.HasOne("MyApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.UserDeviceSession", b =>
                {
                    b.HasOne("MyApp.Domain.Entities.User", "User")
                        .WithMany("DeviceSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.UserExternalLogin", b =>
                {
                    b.HasOne("MyApp.Domain.Entities.User", "User")
                        .WithMany("ExternalLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("MyApp.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApp.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePolicies");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.User", b =>
                {
                    b.Navigation("DeviceSessions");

                    b.Navigation("ExternalLogins");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
